# Generated by Django 3.2.4 on 2021-11-10 10:04

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20211110_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text1',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text1'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text2',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text2'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text3',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text3'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text4',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text4'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text5',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text5'),
        ),
    ]
